### ISSUE TITLE
`tuffix installed` prints base twice

### ISSUE THREAD

**Issue by kevinwortman** [JaredDyreson/Tuffix-Lib#1]
As stated above, `tuffix installed` prints out base twice instead of just once. Here is a screen shot: [https://github.com/CSUF-Tuffix/Tuffix-2/raw/master/images/TuffixInstalled.png](https://github.com/CSUF-Tuffix/Tuffix-2/raw/master/images/TuffixInstalled.png)

**Comment by JaredDyreson** [comment]
There must be a bug in rewrite_state, which was an issue that plagued me a while back. Thank you for bringing it to my attention and I'll fix that ASAP

**Comment by kevinwortman** [comment]
Thanks!

**Comment by JaredDyreson** [comment]
This issue seems to have been fixed in the latest commit.

**Comment by kevinwortman** [comment]
Great! When you push that commit, please close this issue.
