### ISSUE TITLE
Remove "C" from course keywords

### ISSUE THREAD

**Issue by kevinwortman** [JaredDyreson/Tuffix-Lib#4]
Could we remove the leading "C" from course keywords, so that e.g. "C481" is simply "481"? The leading C is necessary in the Python source code since 481 is not a legal identifier. But that's an implementation detail that we should hide from end users. Thanks.

**Comment by JaredDyreson** [comment]
This has been addressed in the last two commits, `tuffix list` should only print out the course number without a preceding 'C'

**Comment by kevinwortman** [comment]
Great! When you push that commit, please close this issue.
