### ISSUE TITLE
pycairo dependency

### ISSUE THREAD

**Issue by kevinwortman** [JaredDyreson/Tuffix-Lib#5]
The code needs the `pycairo` package, but it is not listed as a .deb dependency. `pycairo` seems to be preinstalled on Ubuntu Desktop, but on other Ubuntu variants it's not, and the install breaks.

**Comment by JaredDyreson** [comment]
Addressing in Tuffix-Website repository [pull request](https://github.com/CSUF-Tuffix/Tuffix-Website/pull/3), closing here
